### ISSUE TITLE
Getting 'TypeError: Cannot read property 'info' of undefined'

### ISSUE THREAD

**Issue by mgoldber** [helloalexdodd/full-stack-expense-tracker#1]
It looks like it's something with the configuration of 'logger'. Is there a separate install for this, or could it not be referencing the folder in the appropriate way?

https://github.com/helloalexdodd/full-stack-expense-tracker/blob/5880847c73522e9e5e360f4047ad40b050f1d1c1/server/server.js#L23

**Comment by mgoldber** [comment]
Nevermind, I see the alias script now. I wonder if that could be combo'd with another script.

**Comment by helloalexdodd** [comment]
That's a great idea. I was just going to update the readme, but I'll combine it with the development script for ease.

**Comment by helloalexdodd** [comment]
Fixed!
