### ISSUE TITLE
Obfuscation Needed!

### ISSUE THREAD

**Issue by mgoldber** [helloalexdodd/full-stack-expense-tracker#4]
Should obfuscate the password being used for your recovery email. Stranger danger!

https://github.com/helloalexdodd/full-stack-expense-tracker/blob/4c53c3d1b2f68b1ad30113052fab3289e7de01c1/server/lib/controllers/users/forgot-password.js#L23

**Comment by helloalexdodd** [comment]
THANK YOU!
