### ISSUE TITLE
PORT is always required in .env

### ISSUE THREAD

**Issue by mgoldber** [helloalexdodd/full-stack-expense-tracker#7]
Just a README update: 

You will also need to create environment variables for the email and password if you want to test the Forgot Password functionality locally. Otherwise everthing should work as is.
-> Add something about PORT here.

**Comment by helloalexdodd** [comment]
the server.js file is setup with the PORT as such 
```
const PORT = config.get('port') || 5000;
```

providing a fallback. Do you still think this change is needed?

**Comment by mgoldber** [comment]
I think it might be similar bug to the email address and password being required even if not testing that functionality. This is the error I got in the log:

Error: Configuration property "port" is not defined
       at Config.get (/Users/markgoldberg/Desktop/full-stack-expense-tracker/server/node_modules/config/lib/config.js:182:11)
       at Object.<anonymous> (/Users/markgoldberg/Desktop/full-stack-expense-tracker/server/server.js:22:21)

**Comment by helloalexdodd** [comment]
ahhhhh. okay I've updated the config file with fallbacks to prevent the need for a .env unless using the forgot password functionality.
